### ISSUE TITLE
完整数据集请求

### ISSUE THREAD

**Issue by yan-muzhou** [ChenDelong1999/MEP-3M#1]
我想要获得完整的数据集并且已经发送了邮件，但一直没有回应，可以请你们查看邮件或者有其他获取完整数据集的方式吗？

**Comment by ChenDelong1999** [comment]
你好，感谢关注！完整数据集现已公开，请查看 readme.md。

**Comment by yan-muzhou** [comment]
好的，感谢！

**Comment by birdy-yjp** [comment]
请问获得数据集了吗？现在看仍然是image data under preparation？
